server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com  #自定义服务名称
    prefer-ip-address: true  # true 表示访问路径可以显示 IP 地址


info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
zuul:
  routes:
    users:
      #before  http://myzuul.com:9527/microservicecloud-dept/dept/list
      serviceId: microservicecloud-dept
      # after http://myzuul.com:9527/mydept/dept/list
      path: /mydept/**
  # ignored-services 将原来真实的服务名隐藏掉,也就是说通过元真实服务名不能再正常访问了
  ignored-services: microservicecloud-dept


